security:
    providers:
        auth0:
            id: App\Security\Auth0\Auth0UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: auth0
            custom_authenticators:
                - App\Security\Auth0\Auth0Authenticator