security:
    enable_authenticator_manager: true
    providers:
        token_user_provider:
            id: App\Security\User\TokenUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        registration:
            pattern: ^/api/v1/register
            stateless: true
            provider: token_user_provider
            custom_authenticators:
                - App\Security\TokenAuthenticator

        api:
            pattern: ^/api/v1
            stateless: true
            provider: token_user_provider
            custom_authenticators:
                - App\Security\TokenAuthenticator

    access_control:
        - { path: '^/api/v1/listings/index', roles: 'PUBLIC_ACCESS' }
        - { path: '^/api/v1/listings', roles: ['ROLE_ADMIN', 'ROLE_LANDLORD'] }
    #    - { path: ^/profile/setup, allow_if: "not is_granted('ROLE_TENANT') or not is_granted('ROLE_LANDLORD')" }
