parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Cimi\ChatBundle\:
    resource: '../../../src/'
    exclude:
      - '../../../src/DependencyInjection/'
      - '../../../src/Entity/'

  Cimi\ChatBundle\Controller\TestController: ~