App\PropertyListing\Dto\PropertyListing:
  properties:
    id:
      - NotNull:    { groups: [ update, patch ] }
    title:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [create, update, patch] }
    description:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [create, update, patch] }
    lat:
      - NotBlank: { allowNull: true, groups: [ create, update, patch ] }
      - NotNull: { groups: [ create ] }
    lon:
      - NotBlank: { allowNull: true, groups: [ create, update, patch ] }
      - NotNull: { groups: [ create ] }
    amenities:
      - All:
          - Type: { type: [ integer ], groups: [ create, update, patch ] }
          - NotBlank: { allowNull: true, groups: [ create, update, patch ] }
          - NotNull: { groups: [ create ] }
          - App\Amenity\Validator\ExistingAmenity: {groups: [create, update, patch]}

App\Amenity\Dto\Amenity:
  properties:
    id:
      - NotNull:    { groups: [ update, patch ] }
    name:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [create, update, patch] }

App\AppUser\Dto\AppUser:
  constraints:
      - App\AppUser\Validator\UniqueUser:
          groups: [create]
#          appUserRepository: App\AppUser\Repository\AppUserRepository
#          fields: [userIdentifier, displayName]
#          groups: [create, update, patch]
#          message: 'User with this identifier already exists.'
  properties:
    id:
      - NotNull:    { groups: [ update, patch ] }
    userIdentifier:
      - NotNull:    { groups: [ create ] }
      - NotBlank:   { groups: [ create ] }
#    email:
#      - NotBlank: { groups: [ create, update, patch ] }
#      - NotNull: { groups: [ create ] }
#      - Length: { min: 2, max: 255, groups: [ create, update, patch ] }
    role:
      - NotBlank: { allowNull: true, groups: [ create, update, patch ] }
      - NotNull: { groups: [ create ] }

    displayName:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [ create, update, patch ] }
    firstName:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [ create, update, patch ] }
    lastName:
      - NotBlank:   { allowNull: true, groups: [ create, update, patch ] }
      - NotNull:    { groups: [ create ] }
      - Length:     { min: 2, max: 255, groups: [ create, update, patch ] }