university_controller:
    resource:
        path: ../src/University/Controller/
        namespace: App\University\Controller
    type: attribute

amenity_controller:
    resource:
        path: ../src/Amenity/Controller/
        namespace: App\Amenity\Controller
    type: attribute

property_listing_controller:
    resource:
        path: ../src/PropertyListing/Controller/
        namespace: App\PropertyListing\Controller
    type: attribute


app_user_controller:
    resource:
        path: ../src/AppUser/Controller/
        namespace: App\AppUser\Controller
    type: attribute