amenity_controller:
    resource:
        path: ../src/Amenity/Controller/
        namespace: App\Amenity\Controller
    type: attribute

property_listing_controller:
    resource:
        path: ../src/PropertyListing/Controller/
        namespace: App\PropertyListing\Controller
    type: attribute